### ISSUE TITLE
Data Cleanup

### ISSUE THREAD

**Issue by lapost48** [onTheRed/FAA-Rules-Phase-Calculator#3]
We need to clean the data based on the notes from the Data Mining class attached below. I think it would be best if we had a program that could clean all of the data based on these notes that we can package along with the rest of the project. It isn't in the spec but it is important for the usability of the project.

Lecture Slides:
https://drive.google.com/open?id=0B1sSt2gLlWKzWmFTMTZnd24yMXZjd1RKRHZfMGxDdVl1RnJN

R pdf:
https://drive.google.com/open?id=0B1sSt2gLlWKzOVQyOWF0YUhuQm5iVS1XbXBHOVRWUVJ6RU13

**Comment by lapost48** [comment]
I guess we aren't actually cleaning data in the database and are instead moving that responsibility to the Java portion of the project.

**Comment by smenon18** [comment]
We technically "cleaned" it a bit by further seperating the rows by acid and implementing a primary key, so you guys are just moving the rest of the "cleaning" to java
