### ISSUE TITLE
Take Dictionary from JSON conversion and format with different periods

### ISSUE THREAD

**Issue by johnsbuck** [onTheRed/FAA-Rules-Phase-Calculator#4]
We need to have the dictionary from JSON to have periods based on the timestamp. Each period should be a one minute range starting from the first timestamp.

**Comment by winstoncheong** [comment]
Are you asking me to make a test.json file that matches better what kind of data well be passed around?

**Comment by smenon18** [comment]
I think you need to work on a method that takes the json and separate the data into periods of a minute

**Comment by johnsbuck** [comment]
Pretty much you are getting timestamps (integer), altitudes, and speed. They will be a set for each query received and will only receive them from one ac_id (or aircraft).

Your job is to not only receive the JSON and convert it to some Python object, but to then divide the queries into periods, each period being 1 minute long. We will then use the periods to receive an average on altitude and speed for that time, including the minimum and maximum.

**Comment by johnsbuck** [comment]
You don't have to do the minimum/maximum stuff, the module will do that. All you need to do is make the periods.

**Comment by winstoncheong** [comment]
Resolved
